services:
  app:
    container_name: app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - target=dev # Dockerfileに対応する名前をしている
    volumes:
      - ./:/app
    depends_on:
      - db # dbが立ち上がってから起動
    environment:
      GO_ENV: development
      DB_HOST: roten-app-db
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: roten_app
      SENDER_MAIL_ADDRESS: roten.ishikawa.kosen@gmail.com
      FRONT_ENDPOINT: http://localhost:3000
    tty: true
    ports:
      - 8081:80

  doc:
    image: swaggerapi/swagger-ui:latest
    container_name: doc
    restart: always
    volumes:
      - ./docs/openapi.yml:/usr/share/nginx/html/openapi.yml
    environment:
      - URL=http://localhost/openapi.yml
      - SWAGGER_JSON=./docs/openapi.yml
    ports:
      - 80:8080
  db:
    image: mysql:8.0.31
    platform: linux/amd64
    container_name: roten-app-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: roten_app
    volumes:
      - roten-app-db-data:/var/lib/mysql # データはdocker上で管理
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
  panel:
    image: "adminer:latest"
    restart: always
    ports:
      - 8082:8080
  aws:
    image: localstack/localstack
    ports:
      - 4566:4566
      - 4510-4559:4510-4559
    tty: true
    environment:
      - SERVICES=ses
      - DEFAULT_REGION=ap-northeast-1
volumes: # dockerでデータを管理
  roten-app-db-data:
  roten-app-redis-data:
